{
  inputs,
  config,
  ...
}: let
  flakeConfig = config;
in {
  flake.modules.nixos.hyprland = {
    pkgs,
    system,
    ...
  }: {
    imports = [
      flakeConfig.flake.modules.nixos.sddm
    ];

    programs = {
      hyprland = {
        enable = true;
        package = inputs.hyprland.packages.${system}.hyprland;
        portalPackage = inputs.hyprland.packages.${system}.xdg-desktop-portal-hyprland;

        xwayland.enable = true;
      };
    };

    security.pam.services.hyprlock.text = "auth include login";

    environment.systemPackages = with pkgs; [
      feh
      acpi
      xbacklight
      xdpyinfo
      nautilus
    ];

    nix.settings = {
      substituters = ["https://hyprland.cachix.org"];
      trusted-substituters = ["https://hyprland.cachix.org"];
      trusted-public-keys = ["hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc="];
    };
  };

  flake.modules.homeManager.hyprland = {
    inputs,
    system,
    pkgs,
    config,
    lib,
    ...
  }: let
    inherit (config.opts.theme) colors;
    # Hyprland wants bare RRGGBB(AA) inside rgba()/rgb(), no leading '#'.
    hex = c: lib.removePrefix "#" c;

    # Raw Lua, rendered as `(expr)`. Needed for dispatchers and callbacks.
    dsp = lib.generators.mkLuaInline;

    # The static config lives in checked-in .lua files, symlinked into
    # ~/.config/hypr so they can be edited without a rebuild. Only the
    # theme module is generated, from config.opts.theme.colors.
    luaConfig = name: {
      source =
        config.lib.file.mkOutOfStoreSymlink "${config.opts.variables.dotfilesLocation}"
        + "/modules/features/hyprland/config/${name}.lua";
    };

    themeLua = ''
      -- Generated by Home Manager from config.opts.theme.colors.
      local M = {}

      M.colors = ${lib.generators.toLua {} (lib.mapAttrs (_: hex) (lib.filterAttrs (_: lib.isString) colors))}

      --- Hyprland `rgba(RRGGBBAA)` string for a palette entry.
      function M.rgba(name, alpha)
        return "rgba(" .. M.colors[name] .. (alpha or "ff") .. ")"
      end

      return M
    '';

    # Equivalent of home-manager's (unreleased) `extraLuaFiles`: make
    # ~/.config/hypr requireable, then pull in the static modules.
    luaPrelude = ''
      package.path = (os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config"))
        .. "/hypr/?.lua;" .. package.path

      require("look")
      require("rules")
      require("binds")
    '';
  in {
    imports = [
      ./hypridle.nix
      ./wayle
      ./hyprpaper.nix
      ./hyprlock.nix
      flakeConfig.flake.modules.homeManager.satty
      ./hyprsunset.nix
    ];

    home.packages = with pkgs; [
      wev
      playerctl
      nwg-displays
      grim
      slurp
      wayfreeze
      brightnessctl
    ];

    xdg.configFile = {
      "hypr/theme.lua".text = themeLua;
      "hypr/look.lua" = luaConfig "look";
      "hypr/rules.lua" = luaConfig "rules";
      "hypr/binds.lua" = luaConfig "binds";
    };

    wayland.windowManager.hyprland = {
      enable = true;
      package = inputs.hyprland.packages.${system}.hyprland;
      portalPackage = inputs.hyprland.packages.${system}.xdg-desktop-portal-hyprland;
      systemd.variables = ["--all"];
      configType = "lua";
      extraConfig = luaPrelude;
      settings = {
        on = {
          _args = [
            "hyprland.start"
            (dsp ''function() hl.exec_cmd("nm-applet") end'')
          ];
        };
      };
    };
  };

  flake.modules.combined.hyprland = {...}: {
    imports = [flakeConfig.flake.modules.nixos.hyprland];
    hm.imports = [flakeConfig.flake.modules.homeManager.hyprland];
  };
}
