# After adding/changing keys, re-encrypt with:
#   sops updatekeys secrets/secrets.yaml
keys:
  - &gander age124mal4k3zzdt3ukhh7rvv5ug5m5ee68j00dpp3zd4s3s6ryv55rs45vypj
  # - &gosling age1XXXX_REPLACE_WITH_ssh-to-age_OUTPUT
  # - &skein age1XXXX_REPLACE_WITH_ssh-to-age_OUTPUT
  # - &larry age1XXXX_REPLACE_WITH_ssh-to-age_OUTPUT
  # - &nene age1XXXX_REPLACE_WITH_ssh-to-age_OUTPUT
creation_rules:
  - path_regex: modules/shared/sops/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *gander
          # - *gosling
          # - *skein
          # - *larry
          # - *nene
