items:
- checked: false
  date: null
  tags: []
  text: envoy in agent api
- checked: true
  date: null
  tags: []
  text: precommit
- checked: true
  date: null
  tags: []
  text: fix templating
- checked: true
  date: null
  tags: []
  text: add a flag to expose the azure token in actions
- checked: true
  date: null
  tags: []
  text: memory merged
- checked: true
  date: null
  tags: []
  text: ml-reasoning-service-api-key
