[opener]
zen = [
	{ run = 'zen "$1"', desc = "Zen" },
]

[open]
prepend_rules = [
  { mime = "image/*", use = [ "open", "zen", "reveal" ] },
  { mime = "application/pdf", use = [ "zen", "open", "reveal" ] },
]

[preview]
max_width = 1280
max_height = 1920
