{self, ...}: {
  hm.imports = [
    self.homeModules.home
    self.homeModules.advent-of-code
    self.homeModules.ags
    self.homeModules.dunst
    self.homeModules.fish
    self.homeModules.git
    self.homeModules.hyprland
    self.homeModules.kitty
    self.homeModules.lazydocker
    self.homeModules.lazygit
    self.homeModules.nvim
    self.homeModules.sioyek
    self.homeModules.wallpapers
    self.homeModules.zathura
    self.homeModules.langs
    self.homeModules.python3
    self.homeModules.tex
    self.homeModules.anytype
    self.homeModules.bluetooth
    self.homeModules.direnv
    self.homeModules.gcloud
    self.homeModules.hidpi
    self.homeModules.libreoffice
    self.homeModules.modelling
    self.homeModules.obs
    self.homeModules.jetbrains
    self.homeModules.jetbrains-phpstorm
    self.homeModules.jetbrains-goland
    self.homeModules.php
    self.homeModules.programs
    self.homeModules.guiutils
    self.homeModules.utils
    self.homeModules.vscode
    self.homeModules.walker
    self.homeModules.work
    self.homeModules.zen
    self.homeModules.yazi
    self.homeModules.spotify
    self.homeModules.zellij
  ];
}
